salesforce:
  #username: "naiksantosh-bxug@force.com"
  username: "![6JkLmvyBOUI1G87NhFxGeVRDcJqtJUCChACWQmGJvXs=]"
  #password: "Mphasis7$"
  password: "![hw/KjodB8OSGBmYWFoTQOw==]"
  #securityToken: "EY0R4ySwoY5wwebBYUgkOx9QA"
  securityToken: "![icedouEzAOS2BG/DHEsx07vzPkal0Zih9l3qsFDA1Zg=]"

  
